#!/usr/bin/env python
"""Bundle the demurragedesk package + the web adapter into the served zip.

ONE SOURCE OF TRUTH
-------------------
The browser does not get a JavaScript translation of the rules. It gets the
actual ``demurragedesk`` package, byte for byte, zipped straight out of the
repository working tree and imported by Pyodide. There is no second
implementation of 46 CFR part 541 anywhere in this project, so there is nothing
for a JS port to drift away from.

This script is the only way that zip is produced. ``--check`` rebuilds it in
memory and fails if what is committed under site/py/ no longer matches the
Python source, which is what stops the served bundle going stale.

Outputs (all generated -- never hand-edit):
    site/py/demurragedesk.zip
    site/py/demurragedesk.sha256
    site/js/engine-pin.js
"""

from __future__ import annotations

import argparse
import hashlib
import io
import sys
import zipfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
WEB = HERE.parent
REPO = WEB.parent
PKG = REPO / "demurragedesk"
ADAPTER = WEB / "py" / "webapi.py"

ZIP_PATH = WEB / "site" / "py" / "demurragedesk.zip"
SHA_PATH = WEB / "site" / "py" / "demurragedesk.sha256"
PIN_PATH = WEB / "site" / "js" / "engine-pin.js"

#: Fixed timestamp so the same source always produces the same bytes; a
#: build-time mtime would make --check fail for no reason.
FIXED_TIME = (1980, 1, 1, 0, 0, 0)


def _members() -> list[tuple[str, bytes]]:
    """Every file that goes in the bundle, sorted, with its arcname.

    Only .py files, and only from the package directory plus the one adapter.
    Nothing here may shadow a stdlib module: every entry lives under
    ``demurragedesk/`` except ``webapi.py`` itself.
    """
    if not PKG.is_dir():
        raise SystemExit(f"package not found at {PKG}")
    if not ADAPTER.is_file():
        raise SystemExit(f"adapter not found at {ADAPTER}")

    out: list[tuple[str, bytes]] = []
    for path in sorted(PKG.rglob("*.py")):
        if "__pycache__" in path.parts:
            continue
        arc = "demurragedesk/" + path.relative_to(PKG).as_posix()
        out.append((arc, path.read_bytes()))
    out.append(("webapi.py", ADAPTER.read_bytes()))
    out.sort(key=lambda kv: kv[0])

    for arc, _ in out:
        if arc != "webapi.py" and not arc.startswith("demurragedesk/"):
            raise SystemExit(f"refusing to bundle {arc}: would shadow the stdlib")
        if ".." in arc.split("/"):
            raise SystemExit(f"refusing to bundle {arc}")
    return out


def build_bytes() -> bytes:
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        for arc, data in _members():
            info = zipfile.ZipInfo(arc, date_time=FIXED_TIME)
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o644 << 16
            zf.writestr(info, data)
    return buf.getvalue()


def artifacts() -> tuple[bytes, str, str]:
    blob = build_bytes()
    sha = hashlib.sha256(blob).hexdigest()
    sha_text = f"{sha}  demurragedesk.zip\n"
    pin_text = (
        "// GENERATED by scripts/build_engine.py -- do not edit.\n"
        "// Second, independent pin on the engine bundle: the worker refuses to\n"
        "// import a zip whose sha256 does not match BOTH this constant and the\n"
        "// served .sha256 file.\n"
        f'export const ENGINE_SHA256 = "{sha}";\n'
    )
    return blob, sha_text, pin_text


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--check",
        action="store_true",
        help="verify the committed bundle matches the Python source; write nothing",
    )
    args = ap.parse_args(argv)

    blob, sha_text, pin_text = artifacts()
    expected = [
        (ZIP_PATH, blob),
        (SHA_PATH, sha_text.encode()),
        (PIN_PATH, pin_text.encode()),
    ]

    if args.check:
        stale = []
        for path, want in expected:
            if not path.exists():
                stale.append(f"{path.relative_to(WEB)} is missing")
            elif path.read_bytes() != want:
                stale.append(f"{path.relative_to(WEB)} is stale")
        if stale:
            print("ENGINE BUNDLE OUT OF DATE:", file=sys.stderr)
            for line in stale:
                print(f"  - {line}", file=sys.stderr)
            print("  run: python scripts/build_engine.py", file=sys.stderr)
            return 1
        print(f"engine bundle is current ({sha_text.split()[0]})")
        return 0

    for path, data in expected:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)
    print(f"wrote {ZIP_PATH.relative_to(WEB)} ({len(blob)} bytes)")
    print(f"sha256 {sha_text.split()[0]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
